name: moll
description: Moll

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

  #localization
  intl: ^0.17.0

  # ROUTER
  auto_route: ^4.2.1

  #BLOC
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3

  get_it: ^7.2.0

  #db
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  sqflite: any
  uuid: ^3.0.6
  flutter_secure_storage: ^5.0.2

  connectivity_plus: ^2.3.0

  modal_bottom_sheet: ^2.0.1
  shimmer: ^2.0.0
  flare_flutter: ^3.0.2
  appmetrica_plugin: ^0.1.0
  rxdart: ^0.27.3
  decimal: ^2.2.0
  logger: ^1.1.0

  firebase_crashlytics: ^2.8.0
  firebase_core: ^1.17.0

  ping_discover_network: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^4.2.0

  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter:
 # assets  fluttergen -c pubspec.yaml


  assets:
#    - assets/images/
#    - assets/icons/
    - assets/icons/bootstrap-icons-1.9.0/
#    - assets/animations/
#    - assets/certificates/

  fonts:
    - family: Integron
      fonts:
        - asset: assets/fonts/Integron.ttf
    - family: MPLUS
      fonts:
        - asset: assets/fonts/MPLUS-Black.ttf
        - asset: assets/fonts/MPLUS-Bold.ttf
        - asset: assets/fonts/MPLUS-ExtraBold.ttf
        - asset: assets/fonts/MPLUS-Light.ttf
        - asset: assets/fonts/MPLUS-Medium.ttf
        - asset: assets/fonts/MPLUS-Regular.ttf
        - asset: assets/fonts/MPLUS-Thin.ttf
    - family: Moll
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
  uses-material-design: true
flutter_intl:
  enabled: true